name: CLI Tests

on:
  push:
    branches: [master, main, force_test, release-*]
    tags: ['*']
  pull_request:
    branches: ['**']

env:
  golang-version: 1.18.1
  golangci-lint-version: v1.45.2
  # cert-manager-version needs to be also updated in cli/pkg/otel-utilities.go
  cert-manager-version: v1.8.0

jobs:
  build:
    name: Build and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go ${{ env.golang-version }}
        uses: actions/setup-go@v3.0.0
        with:
          go-version: ${{ env.golang-version }}
        id: go

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ env.golangci-lint-version }}
          working-directory: cli
          args: --timeout=5m

      - name: Format
        working-directory: cli
        run: |
          make go-fmt
          git diff --exit-code

      - name: Vet
        working-directory: cli
        run: |
          make go-vet
          git diff --exit-code

      - name: Build
        working-directory: cli
        run: |
          make build

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go ${{ env.golang-version }}
        uses: actions/setup-go@v3.0.0
        with:
          go-version: ${{ env.golang-version }}

      - name: Unit-Tests
        working-directory: cli
        run: |
          make unit-tests

      - name: Dependency-Tests
        working-directory: cli
        run: |
          go test -v ./tests/dependency-tests

  e2e:
    name: E2E tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kube-version:
          - "1.21"
          - "1.22"
          - "1.23"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go ${{ env.golang-version }}
        uses: actions/setup-go@v3.0.0
        with:
          go-version: ${{ env.golang-version }}

      - name: Start kuberenetes cluster
        working-directory: cli
        env:
          KUBE_VERSION: ${{ matrix.kube-version }}
        run: |
          make start-kind

      - name: Install cert-manager
        working-directory: cli
        run: |
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/${{ env.cert-manager-version }}/cert-manager.yaml

      - name: Build
        working-directory: cli
        run: |
          make build

      - name: Wait for cluster to finish bootstraping
        run: kubectl wait --for=condition=Ready pods --all --all-namespaces --timeout=300s

      - name: Helm tests
        working-directory: cli
        env:
          KUBE_VERSION: ${{ matrix.kube-version }}
        run: |
          make helm-tests

      - name: E2E tests
        working-directory: cli
        env:
          KUBE_VERSION: ${{ matrix.kube-version }}
        run: |
          make e2e-tests

  # Added to summarize the matrix
  tests-result:
    name: e2e results
    if: always()
    needs:
      - e2e
    runs-on: ubuntu-latest
    steps:
      - name: Mark the job as a success
        if: needs.e2e.result == 'success'
        run: exit 0
      - name: Mark the job as a failure
        if: needs.e2e.result != 'success'
        run: exit 1
